rss_parser/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

web/urls.py
from django.urls import path
from web.views import *

app_name = 'web'

urlpatterns = [
    path('', index, name='index'),
    path('add_rss', add_rss, name='add_rss'),
    path('delete_rss', delete_rss, name='delete_rss'),
    path('get_rss', get_rss, name='get_rss'),
     path('export_rss', export_rss, name='export_rss'),
]

web/models.py
from django.db import models

class Feed(models.Model):
    url = models.CharField(max_length=1024)

web/views.py
import feedparser
import json
import schedule
from threading import Thread
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from time import sleep

from web.models import Feed

def index(request):
    context = {
        "feeds": Feed.objects.all().order_by('-pk')
    }
    return render(request, 'index.html', context)

def add_rss(request):
    rss = request.POST.get('rss', None)
    feed = Feed.objects.get_or_create(url=rss)
    Thread(target=update_rss).start()
    return redirect('web:index')

@csrf_exempt
def delete_rss(request):
    Feed.objects.filter(pk=request.POST.get('rss', None)).delete()
    Thread(target=update_rss).start()
    return redirect('web:index')

@csrf_exempt
def get_rss(request):
    f = open('merged_rss.json')
    data = json.load(f)
    f.close()

    return JsonResponse(data, safe=False)

def export_rss(request):
    f = open('merged_rss.json')
    json_object = json.load(f)

    response = HttpResponse(content=json_object, content_type='application/json')
    response['Content-Disposition'] = f'attachment; filename=rss_export.json'
    return response


def update_rss():
    print("upd")
    rss_list = list()
    urls = [feed.url for feed in Feed.objects.all().order_by('-pk')]
    for url in urls:
        NewsFeed = feedparser.parse(url)
        data = NewsFeed.entries

        rss_list.extend(data)

    with open('merged_rss.json', 'w') as outfile:
        json.dump(rss_list, outfile)

def run_scheduler():
    update_rss()
    schedule.every(5).minutes.do(update_rss)

    while True:
        try:
            schedule.run_pending()
        except Exception as ex:
            logger.exception(ex)
        sleep(1)

Thread(target=run_scheduler).start()

web/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Лабораторная 1-2</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<div class="container-fluid p-2 bg-primary text-white text-center">
  <h1>Зозуля Антон ФБ-81</h1>
  <h4>Лабораторная работа 1-2</h4>
  <p><a href="https://bitbucket.org/volksjager/lab_1" style="color: white;">Исходный код</a></p>
</div>
<br>
<div class="container-fluid" style="width: 90%;">
  <div class="row">
    <div class="col-md-4">

        <h4>Добавить отслеживание:</h4>
        <form method="POST" action="{% url 'web:add_rss' %}" id="add_rss_form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-group mb-3">
                <input type="text" name="rss" class="form-control" placeholder="Ссылка на RSS">
                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="submit">Добавить</button>
                </div>
            </div>
        </form>
        <hr>
        <h4>Отслеживаемые фиды:</h4>

        <table class="table" style="word-break: break-word;">
            <tbody>
            {% for feed in feeds %}
                <tr>
                    <th scope="row"><a href="{{ feed.url }}" >{{ feed.url }}</a></th>
                    <th scope="row" style="min-width: 100px;">
                        <form action="{% url 'web:delete_rss' %}" method="post">
                            <button type="submit" name="rss" value="{{ feed.pk }}" class="btn btn-danger btn-sm">Удалить</button>
                        </form>
                    </th>
                </tr>
            {% endfor %}
            </tbody>
          </table>
          
    </div>
    <div class="col-md-8">
      <h4>Объединенный фид</h4>
      <p>Обновление данных на беке раз в 5 минут и при обновлении списка отслеживаний. Запрос данных на фронт каждую секунду</p>
        <div class="d-grid gap-2">
            <a class="btn btn btn-success btn-block" href="{% url 'web:export_rss' %}">
                Скачать в json
            </a>
        </div>
      <hr>
      <pre id="newquote"></pre>
    </div>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>

function updateRss() {
    $.ajax({
        type: "POST",
        url: "{% url 'web:get_rss' %}",
        success: function(data)
        {
            var x = data;

            document.querySelector('#newquote').innerHTML = JSON.stringify(x, null, 6)
                .replace(/\n( *)/g, function (match, p1) {
                    return '<br>' + '&nbsp;'.repeat(p1.length);
                });
        }
        
    });
}

$(document).ready(function () {
    updateRss();
    setInterval(updateRss, 1000);
});

</script>

</body>
</html>